<?php

declare(strict_types=1);

namespace L37sg0\DesignPatterns\Behavioral\Iterator;

class BookListReverseIterator extends BookListIterator
{
    public BookList $bookList;

    public Book $book;

    public function __construct(BookList $bookList)
    {
        parent::__construct($bookList);
    }

    public function next()
    {
        parent::next(); // TODO: Change the autogenerated stub
    }

    public function valid()
    {
        parent::valid(); // TODO: Change the autogenerated stub
    }
}